version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  fief-server:
    image: ghcr.io/fief-dev/fief:latest
    container_name: fief-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:\Users\pedro\PycharmProjects\FastAPIProject\files:/data
    command: server /data --console-address ":9001"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
      INFLUXDB_DB: mydb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  postgres_data:
  influxdb_data: