# Exemplo de como o passo completo poderia parecer em seu job:
    name: Executar o Ruff (e torcer para funcionar desta vez)
      uses: astral-sh/ruff-action@v3.2.2 # Você pode usar a versão ou o commit hash, decida-se!
      with:
        # Argumentos passados para o Ruff. Use `ruff --help` para opções. Padrão: `check`.
        # args: '--fix --exit-non-zero-on-fix' # Exemplo de como passar argumentos

        # Diretório onde o Ruff vai procurar seus pecados em Python. Padrão: o workspace todo.
        # src: './meu_projeto_python' # Exemplo

        # Versão específica do Ruff, se você for do tipo controlador. Padrão: a do pyproject.toml ou 'latest'.
        # version: '0.4.0' # Exemplo

        # Se você não confia no 'latest' e quer travar numa versão do seu requirements.txt.
        # version-file: 'requirements-dev.txt' # Exemplo

        # Para os paranoicos: verificar o checksum do Ruff baixado.
        # checksum: 'sha256-...' # Exemplo

        # Token do GitHub para evitar limites de taxa ao baixar o Ruff. Padrão: o token da ação.
        # github-token: ${{ secrets.MEU_TOKEN_SECRETO }} # Exemplo (raramente necessário mudar)

        # O argumento padrão 'check' já está implícito se você não especificar 'args'.
